#!/usr/bin/env bash

export ACTIVE_STORAGE_SERVICE="${ACTIVE_STORAGE_SERVICE:-local}"
export ENABLE_ACCOUNT_SIGNUP="${ENABLE_ACCOUNT_SIGNUP:-true}"
export FORCE_SSL="${FORCE_SSL:-false}"
export FRONTEND_URL="${FRONTEND_URL:-http://127.0.0.1:3000}"
export INSTALLATION_ENV="${INSTALLATION_ENV:-docker}"
export LOG_LEVEL="${LOG_LEVEL:-info}"
export MAILER_SENDER_EMAIL="${MAILER_SENDER_EMAIL:-Chatwoot <accounts@chatwoot.com>}"
export NODE_ENV="${NODE_ENV:-development}"
export POSTGRES_DATABASE="${POSTGRES_DATABASE:-chatwoot}"
export POSTGRES_HOST="${POSTGRES_HOST:-postgres}"
export POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-postgres}"
export POSTGRES_PORT="${POSTGRES_PORT:-5432}"
export POSTGRES_USERNAME="${POSTGRES_USERNAME:-postgres}"
export RAILS_ENV="${RAILS_ENV:-development}"
export RAILS_LOG_TO_STDOUT="${RAILS_LOG_TO_STDOUT:-true}"
export REDIS_PASSWORD="${REDIS_PASSWORD:-redis}"
export REDIS_URL="${REDIS_URL:-redis://:redis@redis:6379}"
export SECRET_KEY_BASE="${SECRET_KEY_BASE:-0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef}"
export SMTP_ADDRESS="${SMTP_ADDRESS:-mailhog}"
export SMTP_PORT="${SMTP_PORT:-1025}"
